name: Despliegue de Aplicación

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Autenticación en GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configuración de gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/region us-central1
      
      # Construir imágenes y subir a Artifact Registry
      - name: Configurar Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build & Push Frontend Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gest-repo/frontend:latest ./frontend
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gest-repo/frontend:latest

      - name: Build & Push Backend Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gest-repo/backend:latest ./backend
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gest-repo/backend:latest

      # Deploy a Kubernetes
      - name: Obtener credenciales cluster
        run: gcloud container clusters get-credentials gest-cluster --region us-central1

      - name: Instalar gke-gcloud-auth-plugin
        run: |
          # Add Google Cloud's official apt repository key
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          # Add the repository to the apt sources list
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
          # Update package lists
          sudo apt-get update
          # Install the gke-gcloud-auth-plugin
          sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin

      - name: Desplegar en GKE
        run: |
          kubectl apply -f k8s/frontend-deployment.yml
          kubectl apply -f k8s/backend-deployment.yml
          kubectl apply -f k8s/services.yml
          kubectl apply -f k8s/ingress.yml

      - name: Validar despliegue de la aplicación
        run: |
          echo "Esperando por la dirección IP pública del Ingress..."
          INGRESS_IP=""
          for i in {1..30}; do
            INGRESS_IP=$(kubectl get ingress project-management-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            if [ -n "$INGRESS_IP" ]; then
              echo "Ingress IP obtenida: http://$INGRESS_IP"
              break
            fi
            echo "El Ingress aún no tiene una IP. Esperando 10 segundos..."
            sleep 10
          done
          
          if [ -z "$INGRESS_IP" ]; then
            echo "❌ Error: El Ingress no obtuvo una dirección IP a tiempo."
            exit 1
          fi

          # --- Validar el estado de la aplicación ---
          echo "Validando el estado de la aplicación en http://$INGRESS_IP/api/health"
          HEALTH_URL="http://$INGRESS_IP/api/health"
          for i in {1..30}; do
            if curl --output /dev/null --silent --head --fail "$HEALTH_URL"; then
              echo "✅ La aplicación está saludable y respondió correctamente."
              break
            fi
            echo "La aplicación no está lista. Esperando 10 segundos..."
            sleep 10
          done

          if [ $? -ne 0 ]; then
              echo "❌ Error: La aplicación no respondió a tiempo en la URL de salud."
              exit 1
          fi

          # --- Probar el endpoint de registro ---
          echo "Probando el endpoint de registro..."
          PAYLOAD='{"name": "testuser", "email": "testuser@example.com", "password": "TestPassword123"}'
          RESPONSE=$(curl -s -X POST "http://$INGRESS_IP/api/auth/register" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD")

          # Verifica si la respuesta contiene un token de autenticación
          if echo "$RESPONSE" | grep -q "token"; then
            echo "✅ El registro de usuario fue exitoso y se recibió un token."
            echo "Respuesta de la API:"
            echo "$RESPONSE"
          else
            echo "❌ El registro de usuario falló."
            echo "Respuesta de la API:"
            echo "$RESPONSE"
            exit 1
          fi