name: Diagrama de Infraestructura

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Install Graphviz
        run: sudo apt-get install -y graphviz
      
      - name: Install terraform-docs
        run: |
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/
      
      - name: Generate Terraform Graph
        working-directory: infra
        run: |
          terraform init
          
          # Enfoque alternativo: generar directamente la imagen sin usar graph.dot
          echo "Generando imagen directamente con terraform graph..."
          terraform graph | dot -Tpng > terraform-graph.png
          
          # Si el enfoque directo falla, intentar con un enfoque más seguro
          if [ ! -s terraform-graph.png ]; then
            echo "El enfoque directo falló. Usando método alternativo..."
            
            # Crear un archivo DOT simplificado que seguramente funcionará
            echo "digraph G {" > simple-graph.dot
            echo "  rankdir = LR;" >> simple-graph.dot
            
            # Extraer nodos y relaciones básicas
            terraform state list 2>/dev/null | while read resource; do
              echo "  \"$resource\" [shape=box];" >> simple-graph.dot
            done
            
            # Agregar algunos nodos estáticos para asegurar que haya contenido
            echo "  \"google_container_cluster\" [shape=box];" >> simple-graph.dot
            echo "  \"google_compute_network\" [shape=box];" >> simple-graph.dot
            echo "  \"google_compute_subnetwork\" [shape=box];" >> simple-graph.dot
            echo "  \"google_compute_network\" -> \"google_compute_subnetwork\";" >> simple-graph.dot
            echo "  \"google_compute_subnetwork\" -> \"google_container_cluster\";" >> simple-graph.dot
            
            echo "}" >> simple-graph.dot
            
            # Generar imagen con el archivo simplificado
            dot -Tpng simple-graph.dot -o terraform-graph.png
          fi
      
      - name: Generate Infrastructure Documentation
        working-directory: infra
        run: |
          terraform-docs markdown . > infra-docs.md
      
      - name: Commit and Push Diagram
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          mkdir -p docs/diagrams
          cp infra/terraform-graph.png docs/diagrams/
          cp infra/infra-docs.md docs/
          git add docs/diagrams/terraform-graph.png docs/infra-docs.md
          git commit -m "Actualizar diagrama de infraestructura [skip ci]" || echo "No changes to commit"
          git push